{% set name = "vaex-astro" %}
{% set version = "0.7.0" %}
{% set sha256 = "9127e6bbb4db496dac61052d305d2083a2a447dcba244f1d4032a6f3a3797922" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - vaex-core >=1.0.0,<2

test:
  imports:
    - vaex.astro

about:
  home: https://www.github.com/maartenbreddels/vaex
  doc_url: https://docs.vaex.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Astronomy related transformations and FITS file support for vaex

extra:
  recipe-maintainers:
    - maartenbreddels
