{% set name = "vaex-astro" %}
{% set version = "0.8.0" %}
{% set sha256 = "7682b650f66da4c71d87f92049e77d91a673e9f29992f6ff8e63bd7f105617dd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - vaex-core >=2.0.0,<3

test:
  imports:
    - vaex.astro

about:
  home: https://www.github.com/maartenbreddels/vaex
  doc_url: https://docs.vaex.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Astronomy related transformations and FITS file support for vaex

extra:
  recipe-maintainers:
    - maartenbreddels
