travis:
  secure:
    BINSTAR_TOKEN: PXX7pOMGWoPuqmXi0LFOIOosdsvGmcNcfIZbIud6JlpHQnaMgPLNfAcT53qKGltncixIrlUTcRxMH0MexwyZIwX09tXJ72nu6v8jJ0/341FMiE37aTr1R2WByasxtmOGWzEmaiSyXhpgtujwWYrtaX0IvuN5O5HxhMXlLpQWm6c73IVVrf4Q4E8igu8nLLuzFx7Tn/zLlYZrx/e3u3bIapaiok9Ep/e4HBIoqAouqIhzJY4rjn4p5CDjPLSVgoh2MXAJu3HLFdSATz8+2w8KlMPwX2zTFYW8l8zihSz9MiuKZrNEQFiTaBtx57jqb3/ToWBl9KCGd2ev4MyacWcKMwImpWefX/c4hzC0PhADClqrnfI3bssJo/KZul1PTLMcczzm4TriD7I/Ngw01/PHX8Tidy1cROVCYNX6W00mH78rpqyfKbk8Pl8mc8IqM5OVxrTAHjycnLGgONNqpObjgmNnBjtoL7TDWXmHTXJGEtytO3SV5s+oxKoKZRBkOWmf6BjkZ6apstvAidq5JEVqogB73RKQQeGrXtcxAe2RznFAx4FIXxIuHsjvGYrAP2OvJG5awEiJFRffQjLvbPLKwFAOngtjqjefRDzAO6vOxgRFPYO7xY+4fKx4GCcS1agLroJlDnFUCGrn1jbmiZ3bAKJ+dekTqiyuKEMccjUQCXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
